### ISSUE TITLE
Only requests to the first domain are successful

### ISSUE THREAD

**Issue by conorgil** [extrabacon/google-oauth-jwt#10]
Sorry the title of the issue is bad. I couldn't figure out how to explain it briefly.

So, I have been debugging our stack all day and I think I have narrowed the problem down to the google-oauth-jwt library.

What I am doing:
1) start the server, which creates a singleton instance of the request-jwt library
2) have user@domainA.com make a first JWT request to Google. It succeeds
3) have user@domainB.com make a first JWT request to Google. It fails.
4) have user@domainA.com make a second JWT request to Google. It succeeds.

After this point, any time user@domainA.com makes a request it will succeed and all other requests with user@domainX.com emails will fail. You can change the order, wait for a while, try a different domain in between requests, etc, etc and user@domainA.com always works while all others fail.

The issue is reproduceable and this pattern is consistent across restarts. I am still debugging and will update with additional details as I find them, but my current thought is that there is a bug in the TokenCache.

**Comment by extrabacon** [comment]
Updated cache key in 0.1.5.
