### ISSUE TITLE
HTTP 400 : {"error":"invalid_grant"} From certain server locations?

### ISSUE THREAD

**Issue by ant-fx** [extrabacon/google-oauth-jwt#12]
Bit of a strange one.

We have a server stats app written in node that updates a Google spreadsheet with info about the server (disk space, average load, etc).

I'm using edit-google-spreadsheet (https://www.npmjs.com/package/edit-google-spreadsheet) which uses google-oauth-jwt.

The project has been tested on various machines without any problems but the same project, with the same config (email, key file, etc) and all work OK. However 4 test machines always fail with the error:

Error: access token request failed (HTTP 400) : {"error":"invalid_grant"}.

Again, these servers are all using exactly the same project unzipped from the same source with the same project.

Is it possible that Google is blocking auth from this server location or could there be a system config issue that we are not aware of?

Many thanks

**Comment by ant-fx** [comment]
Update:

I have done some testing routing my connection through the same servers to simulate access form the same network. The connections work fine which leads me to think this is being caused by a system config issue rather than network issue?

**Comment by ant-fx** [comment]
Found it.. turns out the system time was incorrect on those servers.

Correcting the system time fixes the issue (I presume that the incorrect time broke SSL) causing a certificate error somewhere along the lines.

**Comment by extrabacon** [comment]
An incorrect system clock would also affect the expiration timestamp, yielding an invalid request.
