### ISSUE TITLE
Incompatible with Request 2.55.1

### ISSUE THREAD

**Issue by miccolis** [extrabacon/google-oauth-jwt#14]
Looks like there was a change in the returned object from `initParams` that breaks how jwt passes configuration around. I believe the problem commit is https://github.com/request/request/commit/98e47fb94f0654edfd384891a521f02072bcab84

**Comment by extrabacon** [comment]
Thank you for the report, I will take a look shortly.

**Comment by maurermax** [comment]
+1 :D

**Comment by maurermax** [comment]
forcing an `npm install request@2.54` within the google-oauth-jwt folder temporarily fixes the issue. so limiting the request version in package.json to this would be a very quick fix

**Comment by extrabacon** [comment]
Fixed in 0.1.5.

**Comment by maurermax** [comment]
thanks!
