### ISSUE TITLE
JWT not working on a centOS?

### ISSUE THREAD

**Issue by Roshgar** [extrabacon/google-oauth-jwt#16]
So i'm somewhat intrigued here, and have a few theories but would like to make sure.
I also know this might not be the best place to ask this, but i'm at loss as to where to ask this question.
(StackOverflow just doesn't seem suited for it.)

So, i used this and everything went fine on both my windows machines. However, i tried to deploy my intranet on a centOS machine, and now the JWT request seems to block at an undefined while parsing the information.

(So either the key.pem is not found or invalid.)

So realistically, what could be causing this? I was using relative paths with __dirname in my node.js server. So i know that it can access the file.

However, could the CRLF issue with windows/UNIX cause the .p12 /.pem to be considered invalid once on a UNIX machine? 
I did try to fix that with a `tr -d '\r' < key.pem > fixedKey.pem` but that didn't seem to change a thing.

And also, that would mean that the .p12 file that you download from google takes into account your OS? Would seem somewhat weird.

I'm just kind of stumped here as to why exactly it's failing on the centOS machine. So if anyone has any other ideas or if one of the ones mentionned are the issue, I would be thrilled to here them.

Thank you.

If any details seem to be missing or this is formulated incorrectly/any other clarification process, tell me and i will update accordingly.

**Comment by extrabacon** [comment]
What is happening exactly? Do you get an error? If so, please include it with the full call stack.

**Comment by Roshgar** [comment]
Sorry, had to get the server room open and accessible. The error is the following, seemingly the same error i had when the file did not exist or when i was using a .pem file that didn't match the calendar i was accessing. But this works on my windows... So i really am curious to see if you have an idea on why? :-)

I'm going to keep on fiddling, trying to figure out what changed/could cause this. 
```
SyntaxError: Unexpected token u
    at Object.parse (native)
    at Object.callback (/home/intranet/server.js:62:23)
    at /home/intranet/node_modules/google-oauth-jwt/lib/request-jwt.js:42:29
    at /home/intranet/node_modules/google-oauth-jwt/lib/token-cache.js:63:4
    at Array.forEach (native)
    at fireCallbacks (/home/intranet/node_modules/google-oauth-jwt/lib/token-cache.js:62:25)
    at /home/intranet/node_modules/google-oauth-jwt/lib/token-cache.js:78:13
    at Request._callback (/home/intranet/node_modules/google-oauth-jwt/lib/auth.js:46:12)
    at Request.self.callback (/home/intranet/node_modules/google-oauth-jwt/node_modules/request/request.js:368:22)
    at Request.emit (events.js:98:17)
```

**Comment by extrabacon** [comment]
Ok, so the error is not thrown from the lib, it's thrown from your callback handler. If I go deeper, I can see that your actual attempt to get a token failed (request-jwt.js:42:29). Are you handling the error correctly in your callback?

**Comment by Roshgar** [comment]
I knew the error came from me, i was curious as to what was causing it. And curious as to why exactly the request is failing when it works fine on the windows. :/
All i do in the callback is `console.log(body)` which, when on the centOS, prints a pretty `undefined`
and then `JSON.parse(body)` which is what makes everythign crash because i'm doing a `JSON.parse(undefined)` 

The question is what can be causing this behaviour? I could just not display when the erros occurs, but that would be always. :-/

```
app.get("/getCalendarInfo", function(req, res) {
    request({
      url : 'https://www.googleapis.com/calendar/v3/calendars/' + calendarID + '/events',
      jwt : 
      {
        email: '809193244733-7bbpiel2095hfb2qcreojmptr4qde3h3@developer.gserviceaccount.com',
        keyFile: __dirname + '/Private/key.pem',//'C:/Users/ronan_000/Documents/NodeTesting/Private/key.pem',
        scopes : ['https://www.googleapis.com/auth/calendar.readonly']
      }
    }, function(err, res, body) {
    
        events = JSON.parse(body);
    });

 });
```
As far as i can tell, i am using it in a correct way, and hell, it works on the windows. I'm just frustrated as to why this would not work on unix...

Long-shot, are some of the source files you have different between windows and UNIX systems? (and are thus installed differently when running an npm?)

And sorry for taking your time, but i'm going crazy over why this is happening. And thank you.

**Comment by extrabacon** [comment]
You are not handling the error in your callback. If the error occurs before the HTTP request, you won't get  values for `res` and `body` arguments. You need to look at `err` and handle it appropriately.

**Comment by Roshgar** [comment]
I must have expressed myself in a non clear way but : I know that the request is failing on the centOS machine. I know that what i am getting is an undefined body. I also know that `err.message = "failed to obtain an authentication token, request failed with HTTP code 400: undefined"`

The question is : Are there portability issues between Windows and UNIX for this? 
Such as the CRLF problem 
and/or 
Google not liking the fact that the key was issued for a windows and passed to a UNIX

Other?

If not, are there any other reasons for the request to fail knowing that the request goes through on 2 different windows machines. (Both windows 8) and the paths I use are all relative in my server?

Handling the error doesn't tell me why the request is failing. I know that somehow my request is considered invalid, not built correctly, but as far as i can tell, between UNIX and windows there is no difference in the syntax of http requests. It's a protocol. It shouldn't change there are RFC's to make sure of that.
So really, i'm bemused here.

If you have no idea i'll just close the issue and try to figure it out as best I can.

**Comment by extrabacon** [comment]
I have never witnessed portability issues. The lib has been used thoroughly on many OSes. I don't think centOS is the problem here. I would definitely take a closer look at the key.

Have you tried putting your key in an environment variable instead of a file? That's what I always do for production. It's also much easier to manage.

Instead of:
```js
request({
  url : 'https://www.googleapis.com/calendar/v3/calendars/' + calendarID + '/events',
  jwt : 
  {
    email: 'email@developer.gserviceaccount.com',
    keyFile: __dirname + '/Private/key.pem',
    scopes : ['https://www.googleapis.com/auth/calendar.readonly']
  }
}
```
you could try:
```js
request({
  url : 'https://www.googleapis.com/calendar/v3/calendars/' + calendarID + '/events',
  jwt : 
  {
    email: 'email@developer.gserviceaccount.com',
    key: process.env.MY_KEY,
    scopes : ['https://www.googleapis.com/auth/calendar.readonly']
  }
}
```

**Comment by Roshgar** [comment]
So, i tried your solution, i tried countless things since then, and by using runScope, the request is never detected on the centOS. No answer from google whatsoever. I know that a simple get on www.google.com returns (get made right before calling the jwt request) but the jwt? Seems to not want to move.

I'm now tempted to just pick up my personal computer, hide it in the server room, and pretend everything worked fine. Feel like i'm slowly going insane due to the fact that none of this makes any sense whatsoever...

If you have a last-minute idea, throw it my way, otherwise i'm probably going to go roll up in a ball in a corner somewhere and have my mental break-down.

Today was a Hodor day for me apparently.

**Comment by extrabacon** [comment]
Things you can try:
- Does the server has internet access? Is there an HTTP proxy?
- Activate tracing, attach a debugger, or hack the module source code directly in `node_modules` to make it more verbose.
- Try the token request from your server with curl or wget. The signed JWT you need to send should be logged when tracing is activated. Everything else you need to build the request is in `auth.js`.

You can activate tracing by adding "google-oauth-jwt" to the DEBUG variable (it works with the [debug](https://www.npmjs.com/package/debug) module).

**Comment by Roshgar** [comment]
So, thanks for the ideas, at least got a more specific idea of what the issue was : 
`google-oauth-jwt response from OAuth server: HTTP 400 -> "{\n  \"error\" : \"invalid_grant\"\n}" +235ms`

And am messing around with the other solutions you indicated. However, using CURL i'm getting : missing paramet : grant_type 

So... Am wondering if that's linked, or if i'm just being a fool and not using CURL correctly. But the invalid_grant error seems to be due to false data from what i scrounged up on the web. So yeah. That's another interesting thing to be seen another day!

Thanks for your help today, probably would have hung myself with an RJ-45 otherwise.
Cheers!
(And good work on the package btw. :-) Worked like a charm when i first put it in. Now the issue is coming from my side. What exactly? Hopefully i'll figure it out one day.)

Anyhow, it's 7PM and i'm guessing you've now started the week-end, so have a nice week-end. :-)
If you happen to answer, hey, great. Sadly i won't be able to test anymore seeing as the office will be locked.

**Comment by Roshgar** [comment]
Well, seems like this issue is to be closed. No more time to figure out what exactly is causing this. 

Thanks for the package, (works brilliantly well on any other machine) and the work. :-)
If i ever do find out what this was, i'll update.

**Comment by extrabacon** [comment]
Thank you and good luck.
