### ISSUE TITLE
How to work with the access token?

### ISSUE THREAD

**Issue by cuenta** [extrabacon/google-oauth-jwt#17]
I got the api call using: 

var request = require('google-oauth-jwt').requestWithJWT();
request({
  url: 'https://www.googleapis.com/drive/v2/files',
  jwt: {
    // use the email address of the service account, as seen in the API console
    email: 'my-service-account@developer.gserviceaccount.com',
    // use the PEM file we generated from the downloaded key
    keyFile: 'my-service-account-key.pem',
    // specify the scopes you wish to access - each application has different scopes
    scopes: ['https://www.googleapis.com/auth/drive.readonly']
  }
}, function (err, res, body) {
    console.log(JSON.parse(body));
});

What is the "body" variable, is the API that I should use?
How to continue?

Some help here, please.
                                                                                      Thanks.

**Comment by extrabacon** [comment]
You are using the modified `request` module, provided by `google-oauth-jwt`. It is a popular HTTP client for Node, which you can use to initiate HTTP requests. In this instance, you are using a modified version of the module which handles the authentication automatically (it will request the token, cache it, reuse it and refresh it when necessary).

You can learn more about `request` here: https://github.com/request/request

You can also use `google-oauth-jwt` with the HTTP client of your choice (node http, superagent, etc.), but you need to manually generate the token and then pass it into the authentication header.

**Comment by cuenta** [comment]
Thanks for the answer. I do understand how to work with request. However, I don't know how to access methods provided by the api.

**Comment by extrabacon** [comment]
I see. Unfortunately I cannot help you with that but refer you to the Google docs (Google Drive from your example): https://developers.google.com/drive/web/about-sdk
