### ISSUE TITLE
Moves an event to another calendar, i.e. changes an event's organizer.

### ISSUE THREAD

**Issue by SantoshSKhavekar** [extrabacon/google-oauth-jwt#21]
How to move an event to another calendar i.e changes an event's organizer using Google Move API.

I refereed this https://developers.google.com/google-apps/calendar/v3/reference/events/move but i am continously getting 404 not found.
Error:   {
  "error": {
    "errors": [
      {
        "domain": "global",
        "reason": "notFound",
        "message": "Not Found"
      }
    ],
    "code": 404,
    "message": "Not Found"
  }
}

So I checked this issue ,and I got the reason for this is Permission issue but I have both calendar permission to access.then also i m getting same .Can someone help me?

**Comment by extrabacon** [comment]
This module has nothing to do with the Calendar API, it simply handles authorization on the server-side for all Google APIs. Maybe you could use a more specific module to assist you with this task.
