### ISSUE TITLE
Making Synchronized Calls

### ISSUE THREAD

**Issue by jelissa** [extrabacon/google-oauth-jwt#26]
I have successfully used this package for refreshing the Google service account access token by following the example. The example shows the token being returned in an async function. Please advise if there is a way for the token to be returned with a synchronized function with this package. Thanks!

**Comment by extrabacon** [comment]
No, it is not possible unless you use something like [deasync](https://www.npmjs.com/package/deasync). This is a big hack that you should avoid.
